<a href="https://colab.research.google.com/github/smell0of0chamomile/wind_energy_analysis/blob/main/Wind_electricity_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Part 0 — Initial Data Inspection

In [ ]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [ ]:
!wget https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data%20for%20analysis/owid-energy-data.csv

--2026-09-09 21:22:49--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data%20for%20analysis/owid-energy-data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2 [text/plain]
Saving to: ‘owid-energy-data.csv’

owid-energy-data.cs 100%[===================>]       2  --.-KB/s    in 0s

2026-09-09 21:22:50 (88.8 KB/s) - ‘owid-energy-data.csv’ saved [2/2]

In [ ]:
# Load the raw dataset
df = pd.read_csv("owid-energy-data.csv")

#Initial inspection of the dataset

In [ ]:
df.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,23377.000000,1.889400e+04,1.178000e+04,2070.000000,7903.000000,6338.000000,8057.000000,6015.000000,6337.000000,6311.000000,6379.000000,6332.000000,5827.000000,6293.000000,5145.000000,6405.000000,6486.000000,7168.000000,9922.000000,16562.000000,14808.000000,16822.000000,7142.000000,6379.000000,6378.000000,6056.000000,7913.000000,4103.000000,12745.000000,12978.000000,11086.000000,7882.000000,6267.000000,6293.000000,6526.000000,7208.000000,5145.000000,6405.000000,7182.000000,6379.000000,5643.000000,6293.000000,6405.000000,6343.000000,7025.000000,5145.000000,8.103000e+03,16990.000000,15028.000000,17251.000000,6999.000000,6379.000000,6028.000000,5686.000000,6293.000000,6405.000000,8501.000000,9603.000000,5145.000000,7777.000000,6379.000000,5902.000000,6293.000000,6405.000000,8596.000000,9698.000000,5145.000000,7872.000000,6379.000000,6056.000000,6032.000000,2579.000000,7717.000000,7859.000000,9090.000000,10192.000000,6585.000000,7718.000000,6379.000000,6267.000000,6293.000000,6405.000000,6465.000000,7147.000000,5145.000000,10182.000000,17729.000000,1.557400e+04,17992.000000,7121.000000,6379.000000,6405.000000,9670.000000,5716.000000,3988.000000,6293.000000,8568.000000,5394.000000,5145.000000,7844.000000,5690.000000,6379.000000,7071.000000,13255.000000,5895.000000,6293.000000,6405.000000,8596.000000,9698.000000,5145.000000,7872.000000,6379.000000,2515.000000,6293.000000,6405.000000,8613.000000,9715.000000,5145.000000,7869.000000,6379.000000,2798.000000,6293.000000,6405.000000,8405.000000,9507.000000,5145.000000,7661.000000,6379.000000
mean,1976.238611,1.058587e+08,4.257565e+11,43.478821,1.054261,55.157110,15.092053,70.470840,12.503951,1.961657,0.227463,477.173914,22.886061,27.702002,5805.017576,1682.740233,697.873283,329.176027,18.372174,17.013825,3468.445644,988.387709,17.096442,18.215402,647.694694,4047.756595,803.999005,16.126469,4.237757,83.495942,25909.065818,1.686106,3.278365,96.807083,2457.120618,550.165562,31749.414909,5271.007776,64.951551,86.070842,18.526289,33.585063,1284.206388,925.271589,185.481525,9977.035028,1.150588e+14,17.562448,6655.444324,625.121302,19.838567,20.096151,339.994720,5.826478,7.817137,379.975275,978.136170,121.586482,3449.316152,25.093292,9.337812,11.394548,29.272074,793.534452,1502.892359,262.000847,5723.048326,35.613497,13.929158,0.100134,1.187138,32.428603,5.482232,228.029937,311.943259,91.700227,1123.541072,5.742484,2.811103,3.079873,35.520018,2304.061154,891.481454,44.480053,15967.362333,21.800837,23.929224,2.597502e+04,1230.348417,29.113980,47.759289,42.552750,13.458438,2.122699,32.761339,2.369012,104.393622,71.054787,470.588333,2.422035,0.767520,0.814827,4038.548478,4254.768670,11.091350,22.549305,513.739405,1173.032586,165.644745,4285.046774,29.985851,11.118055,124.399046,5.017572,23.625811,32.996923,10.836904,82.236840,1.115397,0.219811,290.408295,6.021235,48.691258,70.093753,21.368874,214.958756,1.712025,0.518142
std,35.331092,4.720948e+08,3.507870e+12,286.672304,6.641947,180.660546,75.942537,200.084733,53.260917,5.353897,0.662845,241.445513,762.940352,222.550664,8403.058272,5153.876461,1336.220405,1164.958414,615.977900,198.647187,9727.471337,3586.851619,24.001958,19.035019,2579.025994,5085.240923,2687.184828,7.109148,46.829464,497.365885,38288.434931,1.637283,22.531172,498.967723,3166.453431,1807.932233,33139.266340,14359.423360,31.113919,14.523627,308.302491,148.805513,3670.941633,2322.092370,596.454542,21604.974403,1.035721e+16,110.810222,37523.187915,2484.993625,26.575275,18.935070,1384.212978,38.273607,46.671633,1033.366725,3186.970647,380.280837,10375.112748,29.316611,12.138771,112.517531,116.692884,2374.575371,3955.641665,896.772766,13271.243641,31.500371,14.523627,8.912345,41.023108,328.384619,43.785324,852.477993,957.548677,344.330364,2928.630146,12.980330,5.979656,22.063271,233.888768,6079.290681,1920.409283,140.062011,16898.619150,441.906418,213.130041,1.640531e+05,4243.655991,36.294161,20.054097,159.859831,54.228705,7.661298,516.287115,10.578808,731.839644,893.639182,2963.942645,6.119124,3.748829,2.173075,5042.936479,14897.508936,113.451945,101.024862,1572.129562,3693.708702,590.606169,12497.247653,30.603047,13.269040,704.897751,38.692251,179.415255,126.889710,87.116767,302.862172,3.337844,0.766123,6070.498588,34.260035,281.755752,277.601211,127.539439,733.879405,4.962740,1.722173
min,1900.000000,1.776000e+03,1.642060e+08,-100.000000,-59.083984,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-1988.192383,0.000000,0.000000,0.000000,0.000000,-100.000000,-2376.152344,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.039714,-100.000000,-12613.265625,0.000000,0.000000,-49.590828,-9069.921875,0.000000,0.000000,0.000000,0.000000,0.000000,13.873642,-95.244759,-3749.125000,0.000000,0.000000,0.000000,0.000000,-1.000000e+02,-4092.555664,0.000000,0.000000,0.000000,0.000000,0.000000,-81.250000,-441.636841,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-88.208000,-669.798584,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-93.320000,-772.593811,-100.000000,-534.550781,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-73.920525,-4896.019531,0.000000,0.000000,0.000000,0.000000,-100.000000,-6455.246094,0.000000e+00,0.000000,0.000000,8.057851,0.000000,0.000000,0.000000,-100.000000,-48.201965,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-92.640694,-430.246857,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-4.591518,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-46.534790,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1949.000000,1.599088e+06,1.426394e+10,-0.968287,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,297.785004,-4.980017,-1.296743,304.310425,4.348958,0.000000,0.000000,-4.081979,0.000000,0.000000,0.000000,0.000000,2.001090,1.540000,661.866989,2.250000,12.260926,-0.524623,-0.052320,2833.457214,0.768618,-0.668512,-1.397358,249.382179,0.610000,10360.155273,142.379654,42.831250,80.818806,-0.556959,0.000000,11.880710,0.000000,0.000000,613.122192,-8.640907e-01,0.000000,0.000000,0.000000,0.000000,4.941638,0.300000,-3.890323,-0.519444,3.516667,6.543042,0.100000,121.071114,0.595238,1.104125,-0.603973,-0.027778,7.049560,31.638793,0.245000,259.639862,5.744758,3.335745,0.000000,0.000000,-1.424754,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.194517,-1.666351,80.388962,26.569626,0.150000,5097.861328,-3.091551,0.000000,0.000000e+00,0.000000,2.009500,33.958031,0.000000,0.000000,0.000000,-0.270869,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,654.084076,8.002598,-1.338216,-0.061381,5.299162,29.330366,0.220000,208.402298,3.703704,2.126912,10.563920,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.328556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1985.000000,6.951653e+06,4.357680e+10,6.695433,0.000000,0.000000,0.000000,0.875653,0.020000,0.153061,0.000000,523.809998,1.269237,0.023260,2581.504150,47.364048,0.000000,0.270000,2.222490,0.000000,30.579986,1.625831,1.713080,12.558846,12.460000,2578.041382,21.860001,15.473457,2.482933,0.802385,12666.641602,1.250316,2.622683,7.005362,1407.190979,9.595000,24974.669922,406.549225,70.910896,90.364639,4.083236,1.872000,82.808746,90.289925,2.540000,4265.978027,4.166665e+00,0.000000,0.000000,0.000000,9.962173,16.468380,3.330000,2.818549,0.127777,28.391304,138.457489,3.618000,627.570496,13.631289,5.360722,4.363822,1.013568,51.766727,262.954712,6.150000,1480.612915,29.614290,9.635358,0.000000,0.000000,3.319506,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.385522,3.614502,204.001389,155.493668,1.240000,11817.342773,1.755717,0.000000,5.566581e+00,1.895690,8.645124,43.902500,0.555313,0.030000,0.000000,5.055090,0.000000,0.238781,0.000000,19.932589,0.260452,0.000000,0.117503,2567.543213,91.187180,4.528995,0.700990,37.118404,219.620468,4.536000,914.871948,18.614312,6.550673,28.407761,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.349456,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2005.000000,2.581793e+07,1.830576e+11,23.320313,0.000000,0.506788,0.061667,44.131332,0.880000,1.600195,0.049458,650.000000,7.309347,6.111115,8447.372070,446.305176,802.323273,35.634517,9.101838,0.886539,2090.020630,122.957514,31.753622,29.607839,93.567497,5738.090698,156.590927,18.610569,6.301458,16.594395,36635.574219,2.065455,5.971086,41.473282,3521.204041,123.237499,40051.789062,1870.448486,94.197739,96.664253,9.988498,16.273922,440.570404,869.078308,47.000000,10490.071289,1.099160e+01,1.348506,770.654877,62.224195,27.876524,28.062635,40.684999,10.734023,4.756973,157.448563,705.426697,30.505000,2269.736572,41.827560,11.988546,11.180858,10.937038,263.190491,1414.662567,48.857499,5511.770508,59.333043,19.181192,0.510000,2.181921,14.155095,0.000000,25.768055,0.000000,3.982500,150.660278,2.192157,2.136997,6.422746,20.542084,1013.221802,573.940369,12.415000,21160.748047,10.198024,1.756130,2.450072e+03,185.721874,50.498165,60.314556,11.224527,1.642986,0.000000,13.760777,0.441075,39.709867,0.000000,224.509399,1.850513,0.000000,0.706145,5745.675049,772.244720,12.001205,7.877775,190.561798,926.572983,36.343286,3235.735107,50.000000,15.007385,64.151859,0.014104,0.093827,0.884707,0.030000,2.441566,0.294424,0.005892,45.211092,0.095950,0.915601,2.195791,0.133600,25.914005,0.629577,0.074523
max,2025.000000,8.231613e+09,1.301126e+14,6373.061523,144.289948,2587.707520,1366.878296,2450.790527,710.409973,77.586205,7.581715,1306.719971,55400.000000,2811.242188,96194.445312,45850.542969,9421.677734,10538.940430,44965.750000,3189.062500,162212.781250,50618.328125,100.000000,89.157379,31772.349609,56048.726562,31772.349609,68.996422,4462.328613,10790.421875,651836.562500,25.252504,1553.105103,9430.390625,23813.863281,18275.509766,318559.687500,142420.890625,100.000008,100.000000,15299.998047,3625.421875,41278.269531,23813.863281,6921.140137,288358.531250,9.323217e+17,4146.363281,852312.125000,41244.515625,100.000000,91.942146,14570.480469,1749.999878,485.917480,10860.752930,40911.042969,4434.970215,105413.984375,100.000000,71.416672,7518.203613,2359.283203,32850.859375,56048.726562,13538.059570,153153.984375,100.000000,86.126358,66.669998,100.000000,11200.000977,875.458496,7494.947754,8908.019531,2811.570068,24744.818359,88.011482,41.660614,1553.105103,2993.726562,55292.082031,14645.941406,1366.093628,156814.859375,26472.601562,5856.433594,3.443292e+06,52831.050781,100.000000,100.000000,2476.356689,799.739990,89.330002,21131.333984,165.264404,17032.251953,17032.251953,53224.312500,77.586205,48.450413,31.243769,56048.726562,176737.093750,7518.203613,2164.578125,25979.023438,56048.726562,10726.490234,153153.984375,100.000000,86.126358,21800.000000,1123.987549,5150.569336,2079.407959,2778.639893,4584.595703,50.000000,9.881398,242384.859375,642.616699,6124.465332,4015.415771,2713.139893,9315.287109,58.214485,26.085308

In [ ]:
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.87,1.549794,NaN,572.580017,NaN,NaN,NaN,NaN,NaN,76.029999,NaN,NaN,NaN,NaN,20.073397,NaN,378.760010,NaN,378.760010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.529999,NaN,NaN,80.665855,NaN,NaN,NaN,NaN,NaN,164.259995,NaN,NaN,NaN,NaN,NaN,43.367828,NaN,216.869995,NaN,NaN,NaN,NaN,50.430000,NaN,13.314500,NaN,NaN,NaN,NaN,NaN,73.230003,NaN,19.334143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,65.239998,NaN,NaN,NaN,NaN,NaN,17.224627,NaN,NaN,22.799999,16.930000,NaN,NaN,NaN,NaN,NaN,6.019643,4.469849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.230003,NaN,19.334143,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.46,1.594707,NaN,570.270020,NaN,NaN,NaN,NaN,NaN,86.260002,NaN,NaN,NaN,NaN,21.294035,NaN,405.089996,NaN,405.089996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.899994,NaN,NaN,80.944977,NaN,NaN,NaN,NaN,NaN,190.410004,NaN,NaN,NaN,NaN,NaN,47.004372,NaN,231.009995,NaN,NaN,NaN,NaN,54.330002,NaN,13.411835,NaN,NaN,NaN,NaN,NaN,77.190002,NaN,19.055025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,51.230000,NaN,NaN,NaN,NaN,NaN,12.646572,NaN,NaN,22.860001,16.400000,NaN,NaN,NaN,NaN,NaN,5.643190,4.048483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.190002,NaN,19.055025,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.62,1.528198,NaN,572.679993,NaN,NaN,NaN,NaN,NaN,93.430000,NaN,NaN,NaN,NaN,21.567904,NaN,433.190002,NaN,433.190002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.660004,NaN,NaN,82.333389,NaN,NaN,NaN,NaN,NaN,208.919998,NaN,NaN,NaN,NaN,NaN,48.228260,NaN,248.080002,NaN,NaN,NaN,NaN,53.299999,NaN,12.304070,NaN,NaN,NaN,NaN,NaN,76.529999,NaN,17.666613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,54.310001,NaN,NaN,NaN,NaN,NaN,12.537224,NaN,NaN,23.230000,16.610001,NaN,NaN,NaN,NaN,NaN,5.362543,3.834345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.529999,NaN,17.666613,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.44,1.623391,NaN,577.020020,NaN,NaN,NaN,NaN,NaN,102.010002,NaN,NaN,NaN,NaN,22.258347,NaN,458.299988,NaN,458.299988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.910004,NaN,NaN,83.331879,NaN,NaN,NaN,NaN,NaN,226.509995,NaN,NaN,NaN,NaN,NaN,49.423958,NaN,264.450012,NaN,NaN,NaN,NaN,53.209999,NaN,11.610299,NaN,NaN,NaN,NaN,NaN,76.389999,NaN,16.668121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,53.389999,NaN,NaN,NaN,NaN,NaN,11.649574,NaN,NaN,23.180000,15.740000,NaN,NaN,NaN,NaN,NaN,5.057823,3.434432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.389999,NaN,16.668121,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.39,1.689455,NaN,583.640015,NaN,NaN,NaN,NaN,NaN,115.010002,NaN,NaN,NaN,NaN,23.159019,NaN,496.609985,NaN,496.609985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.660004,NaN,NaN,84.303581,NaN,NaN,NaN,NaN,NaN,244.160004,NaN,NaN,NaN,NaN,NaN,49.165344,NaN,289.839996,NaN,NaN,NaN,NaN,52.990002,NaN,10.670345,NaN,NaN,NaN,NaN,NaN,77.949997,NaN,15.696422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,59.490002,NaN,NaN,NaN,NaN,NaN,11.979219,NaN,NaN,24.959999,16.570000,NaN,NaN,NaN,NaN,NaN,5.026077,3.336622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.949997,NaN,15.696422,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [ ]:
df.tail()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
23372,Zimbabwe,2020,ZWE,15526887.0,2.317871e+10,NaN,0.0,0.0,0.0,6.440441,0.10,1.490313,NaN,371.089996,NaN,NaN,NaN,NaN,176.468079,2.74,3.004352,0.591858,1306.886353,20.291876,40.834576,NaN,8.69,559.674316,6.71,NaN,-15.539186,-6.179134,2163.068359,1.448990,NaN,NaN,179.044266,2.78,NaN,NaN,41.430698,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.49,NaN,NaN,NaN,245.380798,3.81,NaN,56.780922,NaN,NaN,NaN,NaN,253.109329,3.93,NaN,58.569302,NaN,1.98,22.784811,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.576176,0.04,NaN,NaN,NaN,NaN,NaN,0.596125,NaN,NaN,0.10,0.0,NaN,NaN,6.440441,0.0,NaN,1.490313,0.0,NaN,432.153595,33.585716,NaN,NaN,NaN,253.109329,3.93,NaN,58.569302,NaN,NaN,NaN,NaN,1.288088,0.02,NaN,0.298063,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23373,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,NaN,0.0,0.0,0.0,6.963251,0.11,1.283547,NaN,269.549988,NaN,NaN,NaN,NaN,158.888718,2.51,19.707773,3.999077,1537.672607,24.290953,29.288216,NaN,10.31,652.646484,8.57,NaN,12.059059,4.050121,2382.434326,1.497045,NaN,NaN,158.888718,2.51,NaN,NaN,29.288216,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.31,NaN,NaN,NaN,375.382507,5.93,NaN,69.194870,NaN,NaN,NaN,NaN,383.611786,6.06,NaN,70.711784,NaN,1.74,16.876818,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.11,0.0,NaN,NaN,6.963251,0.0,NaN,1.283547,0.0,NaN,542.500488,37.635838,NaN,NaN,NaN,383.611786,6.06,NaN,70.711784,NaN,NaN,NaN,NaN,1.266046,0.02,NaN,0.233372,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23374,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,NaN,0.0,0.0,0.0,6.845453,0.11,1.230425,NaN,297.540009,NaN,NaN,NaN,NaN,181.715668,2.92,21.665226,5.262690,1839.164185,29.553642,32.662193,NaN,10.85,675.210632,8.94,NaN,55.118061,20.744144,3633.067383,2.253915,NaN,NaN,181.715668,2.92,NaN,NaN,32.662193,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2.66,NaN,NaN,NaN,365.920593,5.88,NaN,65.771820,NaN,NaN,NaN,NaN,374.632965,6.02,NaN,67.337814,NaN,1.91,17.603685,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.11,0.0,NaN,NaN,6.845453,0.0,NaN,1.230425,0.0,NaN,556.348572,58.379982,NaN,NaN,NaN,374.632965,6.02,NaN,67.337814,NaN,NaN,NaN,NaN,1.866942,0.03,NaN,0.335570,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23375,Zimbabwe,2023,ZWE,16340829.0,NaN,NaN,0.0,0.0,0.0,7.343568,0.12,1.201201,NaN,392.390015,NaN,NaN,NaN,NaN,268.040253,4.38,26.592663,7.859100,2289.525391,37.412743,43.843845,NaN,11.99,733.744873,9.99,NaN,-10.952223,-6.393906,3181.361084,NaN,NaN,NaN,268.040253,4.38,NaN,NaN,43.843845,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.92,NaN,NaN,NaN,334.132385,5.46,NaN,54.654655,NaN,NaN,NaN,NaN,343.311829,5.61,NaN,56.156158,NaN,2.00,16.680567,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.12,0.0,NaN,NaN,7.343568,0.0,NaN,1.201201,0.0,NaN,611.352051,51.986076,NaN,NaN,NaN,343.311829,5.61,NaN,56.156158,NaN,NaN,NaN,NaN,1.835892,0.03,NaN,0.300300,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23376,Zimbabwe,2024,ZWE,16634366.0,NaN,NaN,0.0,0.0,0.0,7.213981,0.12,1.169591,NaN,384.019989,NaN,NaN,NaN,NaN,264.512634,4.40,16.204708,6.062626,2613.587402,43.475368,42.884991,NaN,12.10,727.409790,10.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.512634,4.40,NaN,NaN,42.884991,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,3.94,NaN,NaN,NaN,342.664093,5.70,NaN,55.555553,NaN,NaN,NaN,NaN,352.282745,5.86,NaN,57.115009,NaN,1.84,15.206612,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000000,0.00,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.12,0.0,NaN,NaN,7.213981,0.0,NaN,1.169591,0.0,NaN,616.795410,NaN,NaN,NaN,NaN,352.282745,5.86,NaN,57.115009,NaN,NaN,NaN,NaN,2.404660,0.04,NaN,0.389864,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23377 entries, 0 to 23376
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), object(2)
memory usage: 23.2+ MB

In [ ]:
df.columns.tolist()

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_demand_per_capita',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

#Basic dataset information

In [ ]:
df.isna().sum()

country                                            0
year                                               0
iso_code                                         770
population                                       564
gdp                                             1152
biofuel_cons_change_pct                         1572
biofuel_cons_change_twh                         1256
biofuel_cons_per_capita                         1368
biofuel_consumption                             1248
biofuel_elec_per_capita                         1399
biofuel_electricity                             1321
biofuel_share_elec                              1321
biofuel_share_energy                            1308
carbon_intensity_elec                           1321
coal_cons_change_pct                            1315
coal_cons_change_twh                            1315
coal_cons_per_capita                            1428
coal_consumption                                1308
coal_elec_per_capita                            1354
coal_electricity                                1196
coal_prod_change_pct                             746
coal_prod_change_twh                             412
coal_prod_per_capita                             718
coal_production                                  396
coal_share_elec                                 1196
coal_share_energy                               1309
electricity_demand                              1321
electricity_demand_per_capita                   1399
electricity_generation                          1181
electricity_share_energy                        1436
energy_cons_change_pct                           904
energy_cons_change_twh                           904
energy_per_capita                               1139
energy_per_gdp                                  1393
fossil_cons_change_pct                          1316
fossil_cons_change_twh                          1316
fossil_elec_per_capita                          1354
fossil_electricity                              1196
fossil_energy_per_capita                        1429
fossil_fuel_consumption                         1309
fossil_share_elec                               1196
fossil_share_energy                             1309
gas_cons_change_pct                             1316
gas_cons_change_twh                             1316
gas_consumption                                 1309
gas_elec_per_capita                             1354
gas_electricity                                 1196
gas_energy_per_capita                           1429
gas_prod_change_pct                              882
gas_prod_change_twh                              295
gas_prod_per_capita                              623
gas_production                                   279
gas_share_elec                                  1196
gas_share_energy                                1309
greenhouse_gas_emissions                        1321
hydro_cons_change_pct                           1316
hydro_cons_change_twh                           1316
hydro_consumption                               1309
hydro_elec_per_capita                           1252
hydro_electricity                               1054
hydro_energy_per_capita                         1429
hydro_share_elec                                1181
hydro_share_energy                              1309
low_carbon_cons_change_pct                      1316
low_carbon_cons_change_twh                      1316
low_carbon_consumption                          1309
low_carbon_elec_per_capita                      1252
low_carbon_electricity                          1054
low_carbon_energy_per_capita                    1429
low_carbon_share_elec                           1181
low_carbon_share_energy                         1309
net_elec_imports                                1399
net_elec_imports_share_demand                   1399
nuclear_cons_change_pct                         1428
nuclear_cons_change_twh                         1257
nuclear_consumption                             1249
nuclear_elec_per_capita                         1217
nuclear_electricity                             1019
nuclear_energy_per_capita                       1369
nuclear_share_elec                              1181
nuclear_share_energy                            1309
oil_cons_change_pct                             1316
oil_cons_change_twh                             1316
oil_consumption                                 1309
oil_elec_per_capita                             1354
oil_electricity                                 1196
oil_energy_per_capita                           1429
oil_prod_change_pct                              734
oil_prod_change_twh                              357
oil_prod_per_capita                              695
oil_production                                   341
oil_share_elec                                  1196
oil_share_energy                                1309
other_renewable_consumption                     1309
other_renewable_electricity                     1054
other_renewable_exc_biofuel_electricity         1347
other_renewables_cons_change_pct                1392
other_renewables_cons_change_twh                1316
other_renewables_elec_per_capita                1252
other_renewables_elec_per_capita_exc_biofuel    1425
other_renewables_energy_per_capita              1429
other_renewables_share_elec                     1181
other_renewables_share_elec_exc_biofuel         1347
other_renewables_share_energy                   1309
per_capita_electricity                          1339
primary_energy_consumption                       887
renewables_cons_change_pct                      1316
renewables_cons_change_twh                      1316
renewables_consumption                          1309
renewables_elec_per_capita                      1252
renewables_electricity                          1054
renewables_energy_per_capita                    1429
renewables_share_elec                           1181
renewables_share_energy                         1309
solar_cons_change_pct                           1520
solar_cons_change_twh                           1316
solar_consumption                               1309
solar_elec_per_capita                           1252
solar_electricity                               1054
solar_energy_per_capita                         1429
solar_share_elec                                1181
solar_share_energy                              1309
wind_cons_change_pct                            1508
wind_cons_change_twh                            1316
wind_consumption                                1309
wind_elec_per_capita                            1252
wind_electricity                                1054
wind_energy_per_capita                          1429
wind_share_elec                                 1181
wind_share_energy                               1309
dtype: int64

In [ ]:
df["country"].nunique()

22

In [ ]:
df["year"].min()

1900

In [ ]:
df["year"].max()

2025

In [ ]:
df.duplicated().sum()

0

The first step is to inspect the structure and general characteristics of the raw dataset. This includes checking its size, time range, number of countries, column names, data types, duplicate rows, and missing values.

The following variables are of particular interest for the analysis:

In [ ]:
# Key variables for the analysis
key_columns = [
    "wind_electricity",
    "wind_share_elec",
    "wind_elec_per_capita",
    "country"
]
'''
Missing data analysis

Before cleaning the dataset,
it is necessary to examine how missing values are
distributed across time and countries.
'''
missing_by_year = (
    df.groupby("year")[key_columns]
      .apply(lambda x: x.isna().mean() * 100)
)
display(missing_by_year)

      wind_electricity  wind_share_elec  wind_elec_per_capita  country
year
1900        100.000000       100.000000            100.000000      0.0
1901        100.000000       100.000000            100.000000      0.0
1902        100.000000       100.000000            100.000000      0.0
1903        100.000000       100.000000            100.000000      0.0
1904        100.000000       100.000000            100.000000      0.0
1905        100.000000       100.000000            100.000000      0.0
1906        100.000000       100.000000            100.000000      0.0
1907        100.000000       100.000000            100.000000      0.0
1908        100.000000       100.000000            100.000000      0.0
1909        100.000000       100.000000            100.000000      0.0
1910        100.000000       100.000000            100.000000      0.0
1911        100.000000       100.000000            100.000000      0.0
1912        100.000000       100.000000            100.000000      0.0
1913        100.000000       100.000000            100.000000      0.0
1914        100.000000       100.000000            100.000000      0.0
1915        100.000000       100.000000            100.000000      0.0
1916        100.000000       100.000000            100.000000      0.0
1917        100.000000       100.000000            100.000000      0.0
1918        100.000000       100.000000            100.000000      0.0
1919        100.000000       100.000000            100.000000      0.0
1920        100.000000       100.000000            100.000000      0.0
1921        100.000000       100.000000            100.000000      0.0
1922        100.000000       100.000000            100.000000      0.0
1923        100.000000       100.000000            100.000000      0.0
1924        100.000000       100.000000            100.000000      0.0
1925        100.000000       100.000000            100.000000      0.0
1926        100.000000       100.000000            100.000000      0.0
1927        100.000000       100.000000            100.000000      0.0
1928        100.000000       100.000000            100.000000      0.0
1929        100.000000       100.000000            100.000000      0.0
1930        100.000000       100.000000            100.000000      0.0
1931        100.000000       100.000000            100.000000      0.0
1932        100.000000       100.000000            100.000000      0.0
1933        100.000000       100.000000            100.000000      0.0
1934        100.000000       100.000000            100.000000      0.0
1935        100.000000       100.000000            100.000000      0.0
1936        100.000000       100.000000            100.000000      0.0
1937        100.000000       100.000000            100.000000      0.0
1938        100.000000       100.000000            100.000000      0.0
1939        100.000000       100.000000            100.000000      0.0
1940        100.000000       100.000000            100.000000      0.0
1941        100.000000       100.000000            100.000000      0.0
1942        100.000000       100.000000            100.000000      0.0
1943        100.000000       100.000000            100.000000      0.0
1944        100.000000       100.000000            100.000000      0.0
1945        100.000000       100.000000            100.000000      0.0
1946        100.000000       100.000000            100.000000      0.0
1947        100.000000       100.000000            100.000000      0.0
1948        100.000000       100.000000            100.000000      0.0
1949        100.000000       100.000000            100.000000      0.0
1950        100.000000       100.000000            100.000000      0.0
1951        100.000000       100.000000            100.000000      0.0
1952        100.000000       100.000000            100.000000      0.0
1953        100.000000       100.000000            100.000000      0.0
1954        100.000000       100.000000            100.000000      0.0
1955        100.000000       100.000000            100.000000      0.0
1956        100.000000       100.000000            100.000000      0.0
1957        100.000000       100.000000            100.000000      0.0
1958        100.000000       100.000000            100.000000      0.0
1959        100.000000       100.000000            100.000000      0.0
1960        100.000000       100.000000            100.000000      0.0
1961        100.000000       100.000000            100.000000      0.0
1962        100.000000       100.000000            100.000000      0.0
1963        100.000000       100.000000            100.000000      0.0
1964        100.000000       100.000000            100.000000      0.0
1965         42.767296       100.000000             50.943396      0.0
1966         42.767296       100.000000             50.943396      0.0
1967         42.767296       100.000000             50.943396      0.0
1968         42.767296       100.000000             50.943396      0.0
1969         42.767296       100.000000             50.943396      0.0
1970         42.767296       100.000000             50.943396      0.0
1971         42.767296       100.000000             50.943396      0.0
1972         42.767296       100.000000             50.943396      0.0
1973         42.767296       100.000000             50.943396      0.0
1974         42.767296       100.000000             50.943396      0.0
1975         42.767296       100.000000             50.943396      0.0
1976         43.125000       100.000000             51.250000      0.0
1977         43.125000       100.000000             51.250000      0.0
1978         43.125000       100.000000             51.250000      0.0
1979         43.125000       100.000000             51.250000      0.0
1980         66.296296       100.000000             71.111111      0.0
1981         66.420664       100.000000             71.217712      0.0
1982         66.420664       100.000000             71.217712      0.0
1983         66.420664       100.000000             71.217712      0.0
1984         66.420664       100.000000             71.217712      0.0
1985         64.412811        64.412811             69.039146      0.0
1986         64.539007        64.539007             69.148936      0.0
1987         64.539007        64.539007             69.148936      0.0
1988         64.539007        64.539007             69.148936      0.0
1989         64.539007        64.539007             69.148936      0.0
1990         63.321799        63.321799             68.166090      0.0
1991         63.066202        63.066202             67.944251      0.0
1992         63.698630        63.698630             68.493151      0.0
1993         63.573883        63.573883             68.384880      0.0
1994         63.698630        63.698630             68.493151      0.0
1995         63.822526        63.822526             68.600683      0.0
1996         63.822526        63.822526             68.600683      0.0
1997         63.945578        63.945578             68.707483      0.0
1998         63.945578        63.945578             68.707483      0.0
1999         63.945578        63.945578             68.707483      0.0
2000         25.816993        26.143791             33.986928      0.0
2001         25.816993        26.143791             33.986928      0.0
2002         25.163399        25.490196             33.333333      0.0
2003         24.755700        25.081433             32.899023      0.0
2004         22.149837        22.475570             30.293160      0.0
2005         22.077922        22.402597             30.194805      0.0
2006         21.824104        22.149837             29.967427      0.0
2007         21.824104        22.149837             29.967427      0.0
2008         21.824104        22.149837             29.967427      0.0
2009         21.824104        22.149837             29.967427      0.0
2010         21.824104        22.149837             29.967427      0.0
2011         21.498371        21.824104             29.641694      0.0
2012         21.103896        21.428571             29.220779      0.0
2013         20.779221        21.103896             28.896104      0.0
2014         20.129870        20.454545             28.246753      0.0
2015         20.129870        20.454545             28.246753      0.0
2016         20.129870        20.454545             28.246753      0.0
2017         15.986395        16.326531             24.489796      0.0
2018         15.986395        16.326531             24.489796      0.0
2019         15.986395        16.326531             24.489796      0.0
2020         15.358362        15.699659             23.890785      0.0
2021         15.358362        15.699659             23.890785      0.0
2022         15.358362        15.699659             23.890785      0.0
2023         15.699659        16.382253             24.232082      0.0
2024          8.661417         9.055118             18.503937      0.0
2025          1.886792         1.886792             13.207547      0.0

In [ ]:
# Percentage of missing values by country
missing_by_country = (
    df.groupby("country")[key_columns]
      .apply(lambda x: x.isna().mean() * 100)
)
display(missing_by_country)

,wind_electricity,wind_share_elec,wind_elec_per_capita,country
country,,,,
ASEAN (Ember),0.000000,0.000000,100.000000,0.0
Afghanistan,80.000000,80.000000,80.000000,0.0
Africa,52.000000,68.000000,52.000000,0.0
Africa (EI),0.000000,33.333333,100.000000,0.0
Africa (EIA),100.000000,100.000000,100.000000,0.0
Africa (Ember),0.000000,0.000000,100.000000,0.0
Africa (Shift),100.000000,100.000000,100.000000,0.0
Albania,80.000000,80.000000,80.000000,0.0
Algeria,52.000000,68.000000,52.000000,0.0
American Samoa,44.444444,44.444444,44.444444,0.0
Angola,80.000000,80.000000,80.000000,0.0
Antarctica,100.000000,100.000000,100.000000,0.0
Antigua and Barbuda,44.444444,44.444444,44.444444,0.0
Argentina,51.587302,67.460317,51.587302,0.0
Armenia,23.529412,23.529412,23.529412,0.0
Aruba,35.897436,35.897436,35.897436,0.0
Asia,52.000000,68.000000,52.000000,0.0
Asia (Ember),0.000000,0.000000,100.000000,0.0
Asia Pacific (EI),0.000000,33.333333,100.000000,0.0
Asia and Oceania (EIA),100.000000,100.000000,100.000000,0.0
Asia and Oceania (Shift),100.000000,100.000000,100.000000,0.0
Australia,51.587302,67.460317,51.587302,0.0
Australia and New Zealand (EIA),100.000000,100.000000,100.000000,0.0
Austria,51.587302,67.460317,51.587302,0.0
Azerbaijan,0.000000,0.000000,0.000000,0.0
Bahamas,44.444444,44.444444,44.444444,0.0
Bahrain,80.000000,80.000000,80.000000,0.0
Bangladesh,51.587302,67.460317,51.587302,0.0
Barbados,80.000000,80.000000,80.000000,0.0
Belarus,0.000000,0.000000,0.000000,0.0
Belgium,51.587302,67.460317,51.587302,0.0
Belize,44.444444,44.444444,44.444444,0.0
Benin,44.444444,44.444444,44.444444,0.0
Bermuda,44.444444,44.444444,44.444444,0.0
Bhutan,44.444444,44.444444,44.444444,0.0
Bolivia,79.365079,79.365079,79.365079,0.0
Bosnia and Herzegovina,55.882353,55.882353,55.882353,0.0
Botswana,80.000000,80.000000,80.000000,0.0
Brazil,51.587302,67.460317,51.587302,0.0
British Virgin Islands,45.454545,45.454545,45.454545,0.0
Brunei,80.000000,80.000000,80.000000,0.0
Bulgaria,54.761905,70.634921,54.761905,0.0
Burkina Faso,44.444444,44.444444,44.444444,0.0
Burundi,80.000000,80.000000,80.000000,0.0
CIS (EI),0.000000,33.333333,100.000000,0.0
Cambodia,100.000000,100.000000,100.000000,0.0
Cameroon,80.000000,80.000000,80.000000,0.0
Canada,51.587302,67.460317,51.587302,0.0
Cape Verde,44.444444,44.444444,44.444444,0.0
Cayman Islands,44.444444,44.444444,44.444444,0.0
Central African Republic,45.454545,45.454545,45.454545,0.0
Central America (EI),0.000000,33.333333,100.000000,0.0
Central and South America (EIA),100.000000,100.000000,100.000000,0.0
Central and South America (Shift),100.000000,100.000000,100.000000,0.0
Chad,58.333333,58.333333,58.333333,0.0
Chile,51.587302,67.460317,51.587302,0.0
China,51.587302,67.460317,51.587302,0.0
Colombia,51.587302,67.460317,51.587302,0.0
Comoros,45.454545,45.454545,45.454545,0.0
Congo,80.000000,80.000000,80.000000,0.0
Cook Islands,44.444444,44.444444,44.444444,0.0
Costa Rica,43.478261,43.478261,43.478261,0.0
Cote d'Ivoire,80.000000,80.000000,80.000000,0.0
Croatia,11.111111,11.111111,11.111111,0.0
Cuba,80.000000,80.000000,80.000000,0.0
Curacao,100.000000,100.000000,100.000000,0.0
Cyprus,6.557377,39.344262,6.557377,0.0
Czechia,1.639344,34.426230,1.639344,0.0
Czechoslovakia,100.000000,100.000000,100.000000,0.0
Democratic Republic of Congo,80.000000,80.000000,80.000000,0.0
Denmark,51.587302,67.460317,51.587302,0.0
Djibouti,44.444444,44.444444,44.444444,0.0
Dominica,45.454545,45.454545,45.454545,0.0
Dominican Republic,43.478261,43.478261,43.478261,0.0
EU (Ember),0.000000,0.000000,100.000000,0.0
EU28 (Shift),100.000000,100.000000,100.000000,0.0
East Germany,100.000000,100.000000,100.000000,0.0
East Timor,0.000000,0.000000,0.000000,0.0
Eastern Africa (EI),0.000000,33.333333,100.000000,0.0
Eastern Europe and Eurasia (EIA),100.000000,100.000000,100.000000,0.0
Ecuador,51.587302,67.460317,51.587302,0.0
Egypt,51.587302,67.460317,51.587302,0.0
El Salvador,86.956522,86.956522,86.956522,0.0
Equatorial Guinea,58.333333,58.333333,58.333333,0.0
Eritrea,19.354839,19.354839,19.354839,0.0
Estonia,4.878049,4.878049,4.878049,0.0
Eswatini,80.000000,80.000000,80.000000,0.0
Ethiopia,43.478261,43.478261,43.478261,0.0
Eurasia (EIA),100.000000,100.000000,100.000000,0.0
Eurasia (Shift),100.000000,100.000000,100.000000,0.0
Europe,54.761905,70.634921,54.761905,0.0
Europe (EI),0.000000,33.333333,100.000000,0.0
Europe (EIA),100.000000,100.000000,100.000000,0.0
Europe (Ember),0.000000,0.000000,100.000000,0.0
Europe (Shift),100.000000,100.000000,100.000000,0.0
European Union (27),54.761905,70.634921,54.761905,0.0
Falkland Islands,45.454545,45.454545,45.454545,0.0
Faroe Islands,45.454545,45.454545,45.454545,0.0
Fiji,44.444444,44.444444,44.444444,0.0
Finland,0.000000,32.786885,0.000000,0.0
France,51.587302,67.460317,51.587302,0.0
French Guiana,100.000000,100.000000,100.000000,0.0
French Polynesia,44.444444,44.444444,44.444444,0.0
G20 (Ember),0.000000,0.000000,100.000000,0.0
G7 (Ember),0.000000,0.000000,100.000000,0.0
Gabon,80.000000,80.000000,80.000000,0.0
Gambia,44.444444,44.444444,44.444444,0.0
Georgia,23.529412,23.529412,23.529412,0.0
Germany,51.587302,67.460317,51.587302,0.0
Ghana,80.000000,80.000000,80.000000,0.0
Gibraltar,44.444444,44.444444,44.444444,0.0
Greece,51.587302,67.460317,51.587302,0.0
Greenland,80.000000,80.000000,80.000000,0.0
Grenada,44.444444,44.444444,44.444444,0.0
Guadeloupe,45.454545,45.454545,45.454545,0.0
Guam,44.444444,44.444444,44.444444,0.0
Guatemala,80.000000,80.000000,80.000000,0.0
Guinea,44.444444,44.444444,44.444444,0.0
Guinea-Bissau,44.444444,44.444444,44.444444,0.0
Guyana,58.333333,58.333333,58.333333,0.0
Haiti,44.444444,44.444444,44.444444,0.0
High-income countries,52.000000,68.000000,52.000000,0.0
Honduras,44.444444,44.444444,44.444444,0.0
Hong Kong,0.000000,33.333333,0.000000,0.0
Hungary,52.380952,68.253968,52.380952,0.0
Iceland,0.000000,33.333333,0.000000,0.0
India,51.587302,67.460317,51.587302,0.0
Indonesia,52.000000,68.000000,52.000000,0.0
Iran,51.587302,67.460317,51.587302,0.0
Iraq,52.000000,68.000000,52.000000,0.0
Ireland,51.587302,67.460317,51.587302,0.0
Israel,51.587302,67.460317,51.587302,0.0
Italy,51.587302,67.460317,51.587302,0.0
Jamaica,44.444444,44.444444,44.444444,0.0
Japan,51.587302,67.460317,51.587302,0.0
Jordan,44.444444,44.444444,44.444444,0.0
Kazakhstan,0.000000,0.000000,0.000000,0.0
Kenya,43.478261,43.478261,43.478261,0.0
Kiribati,44.444444,44.444444,44.444444,0.0
Kosovo,46.153846,46.153846,46.153846,0.0
Kuwait,51.587302,67.460317,51.587302,0.0
Kyrgyzstan,23.529412,23.529412,23.529412,0.0
Laos,44.444444,44.444444,44.444444,0.0
Latin America and Caribbean (Ember),0.000000,0.000000,100.000000,0.0
Latvia,0.000000,0.000000,0.000000,0.0
Lebanon,44.444444,44.444444,44.444444,0.0
Lesotho,44.444444,48.888889,44.444444,0.0
Liberia,44.444444,44.444444,44.444444,0.0
Libya,80.000000,80.000000,80.000000,0.0
Lithuania,9.756098,9.756098,9.756098,0.0
Low-income countries,80.000000,80.000000,80.000000,0.0
Lower-middle-income countries,52.000000,68.000000,52.000000,0.0
Luxembourg,0.000000,32.786885,0.000000,0.0
Macao,44.444444,44.444444,44.444444,0.0
Madagascar,80.000000,80.000000,80.000000,0.0
Malawi,44.444444,44.444444,44.444444,0.0
Malaysia,51.587302,67.460317,51.587302,0.0
Maldives,44.444444,44.444444,44.444444,0.0
Mali,44.444444,44.444444,44.444444,0.0
Malta,47.826087,47.826087,47.826087,0.0
Martinique,54.545455,54.545455,54.545455,0.0
Mauritania,44.444444,44.444444,44.444444,0.0
Mauritius,44.444444,44.444444,44.444444,0.0
Mexico,51.587302,67.460317,51.587302,0.0
Micronesia (country),100.000000,100.000000,100.000000,0.0
Middle Africa (EI),0.000000,33.333333,100.000000,0.0
Middle East (EI),0.000000,33.333333,100.000000,0.0
Middle East (EIA),100.000000,100.000000,100.000000,0.0
Middle East (Ember),0.000000,0.000000,100.000000,0.0
Middle East (Shift),100.000000,100.000000,100.000000,0.0
Moldova,23.529412,23.529412,23.529412,0.0
Mongolia,79.365079,79.365079,79.365079,0.0
Montenegro,57.142857,57.142857,57.142857,0.0
Montserrat,44.444444,44.444444,44.444444,0.0
Morocco,51.587302,67.460317,51.587302,0.0
Mozambique,80.000000,80.000000,80.000000,0.0
Myanmar,80.000000,80.000000,80.000000,0.0
Namibia,28.571429,28.571429,28.571429,0.0
Nauru,44.444444,44.444444,44.444444,0.0
Nepal,80.000000,80.000000,80.000000,0.0
Netherlands,51.587302,67.460317,51.587302,0.0
Netherlands Antilles,100.000000,100.000000,100.000000,0.0
New Caledonia,44.444444,44.444444,44.444444,0.0
New Zealand,51.587302,67.460317,51.587302,0.0
Nicaragua,44.444444,44.444444,44.444444,0.0
Niger,80.000000,80.000000,80.000000,0.0
Nigeria,79.365079,79.365079,79.365079,0.0
Niue,45.454545,100.000000,45.454545,0.0
Non-OECD (EI),0.000000,33.333333,100.000000,0.0
Non-OECD (EIA),100.000000,100.000000,100.000000,0.0
Non-OPEC (EI),100.000000,100.000000,100.000000,0.0
Non-OPEC (EIA),100.000000,100.000000,100.000000,0.0
North America,52.000000,68.000000,52.000000,0.0
North America (EI),0.000000,33.333333,100.000000,0.0
North America (Ember),0.000000,0.000000,100.000000,0.0
North America (Shift),100.000000,100.000000,100.000000,0.0
North Korea,80.000000,80.000000,80.000000,0.0
North Macedonia,38.888889,38.888889,38.888889,0.0
Northern Mariana Islands,100.000000,100.000000,100.000000,0.0
Norway,51.587302,67.460317,51.587302,0.0
OECD (EI),0.000000,33.333333,100.000000,0.0
OECD (EIA),100.000000,100.000000,100.000000,0.0
OECD (Ember),0.000000,0.000000,100.000000,0.0
OECD (Shift),100.000000,100.000000,100.000000,0.0
OPEC (EI),100.000000,100.000000,100.000000,0.0
OPEC (EIA),100.000000,100.000000,100.000000,0.0
OPEC (Shift),100.000000,100.000000,100.000000,0.0
Oceania,52.000000,68.000000,52.000000,0.0
Oceania (Ember),0.000000,0.000000,100.000000,0.0
Oman,51.587302,67.460317,51.587302,0.0
Other Africa (EI),100.000000,100.000000,100.000000,0.0
Other Americas (EIA),100.000000,100.000000,100.000000,0.0
Other Asia Pacific (EI),100.000000,100.000000,100.000000,0.0
Other Asia-Pacific (EIA),100.000000,100.000000,100.000000,0.0
Other CIS (EI),100.000000,100.000000,100.000000,0.0
Other Caribbean (EI),100.000000,100.000000,100.000000,0.0
Other Eastern Africa (EI),100.000000,100.000000,100.000000,0.0
Other Europe (EI),100.000000,100.000000,100.000000,0.0
Other Middle Africa (EI),100.000000,100.000000,100.000000,0.0
Other Middle East (EI),100.000000,100.000000,100.000000,0.0
Other North America (EI),100.000000,100.000000,100.000000,0.0
Other Northern Africa (EI),100.000000,100.000000,100.000000,0.0
Other South America (EI),100.000000,100.000000,100.000000,0.0
Other South and Central America (EI),100.000000,100.000000,100.000000,0.0
Other Southern Africa (EI),100.000000,100.000000,100.000000,0.0
Other Western Africa (EI),100.000000,100.000000,100.000000,0.0
Pakistan,51.587302,67.460317,51.587302,0.0
Palestine,10.714286,10.714286,10.714286,0.0
Panama,44.444444,44.444444,44.444444,0.0
Papua New Guinea,44.444444,44.444444,44.444444,0.0
Paraguay,43.478261,43.478261,43.478261,0.0
Persian Gulf (EIA),100.000000,100.000000,100.000000,0.0
Persian Gulf (Shift),100.000000,100.000000,100.000000,0.0
Peru,51.587302,67.460317,51.587302,0.0
Philippines,51.587302,67.460317,51.587302,0.0
Poland,51.587302,67.460317,51.587302,0.0
Portugal,51.587302,67.460317,51.587302,0.0
Puerto Rico,43.478261,43.478261,43.478261,0.0
Qatar,51.587302,67.460317,51.587302,0.0
Rest of World (EI),100.000000,100.000000,100.000000,0.0
Reunion,54.545455,54.545455,54.545455,0.0
Romania,55.555556,71.428571,55.555556,0.0
Russia,0.000000,0.000000,0.000000,0.0
Rwanda,44.444444,44.444444,44.444444,0.0
Saint Helena,45.454545,45.454545,45.454545,0.0
Saint Kitts and Nevis,44.444444,44.444444,44.444444,0.0
Saint Lucia,44.444444,44.444444,44.444444,0.0
Saint Pierre and Miquelon,45.454545,45.454545,45.454545,0.0
Saint Vincent and the Grenadines,44.444444,44.444444,44.444444,0.0
Samoa,44.444444,44.444444,44.444444,0.0
Sao Tome and Principe,45.454545,45.454545,45.454545,0.0
Saudi Arabia,52.000000,68.000000,52.000000,0.0
Senegal,44.444444,44.444444,44.444444,0.0
Serbia,33.333333,33.333333,33.333333,0.0
Serbia and Montenegro,100.000000,100.000000,100.000000,0.0
Seychelles,44.444444,44.444444,44.444444,0.0
Sierra Leone,44.444444,44.444444,44.444444,0.0
Singapore,42.622951,75.409836,42.622951,0.0
Slovakia,4.918033,37.704918,4.918033,0.0
Slovenia,36.111111,36.111111,36.111111,0.0
Solomon Islands,44.444444,44.444444,44.444444,0.0
Somalia,44.444444,44.444444,44.444444,0.0
South Africa,51.587302,67.460317,51.587302,0.0
South America,52.000000,68.000000,52.000000,0.0
South Korea,51.587302,67.460317,51.587302,0.0
South Sudan,0.000000,0.000000,0.000000,0.0
South and Central America (EI),0.000000,33.333333,100.000000,0.0
Spain,51.587302,67.460317,51.587302,0.0
Sri Lanka,0.000000,32.786885,0.000000,0.0
Sudan,58.333333,58.333333,58.333333,0.0
Suriname,80.000000,80.000000,80.000000,0.0
Sweden,51.587302,67.460317,51.587302,0.0
Switzerland,51.587302,67.460317,51.587302,0.0
Syria,80.000000,80.000000,80.000000,0.0
Taiwan,51.587302,67.460317,51.587302,0.0
Tajikistan,23.529412,23.529412,23.529412,0.0
Tanzania,80.000000,80.000000,80.000000,0.0
Thailand,51.587302,67.460317,51.587302,0.0
Togo,44.444444,44.444444,44.444444,0.0
Tonga,44.444444,44.444444,44.444444,0.0
Trinidad and Tobago,52.000000,68.000000,52.000000,0.0
Tunisia,79.365079,79.365079,79.365079,0.0
Turkey,51.587302,67.460317,51.587302,0.0
Turkmenistan,0.000000,0.000000,0.000000,0.0
Turks and Caicos Islands,44.444444,44.444444,44.444444,0.0
Tuvalu,100.000000,100.000000,100.000000,0.0
U.S. Pacific Islands (EIA),100.000000,100.000000,100.000000,0.0
U.S. Territories (EIA),100.000000,100.000000,100.000000,0.0
USSR,78.260870,100.000000,78.260870,0.0
Uganda,44.444444,44.444444,44.444444,0.0
Ukraine,68.333333,68.333333,68.333333,0.0
United Arab Emirates,52.000000,68.000000,52.000000,0.0
United Kingdom,51.587302,67.460317,51.587302,0.0
United States,51.587302,67.460317,51.587302,0.0
United States Pacific Islands (Shift),100.000000,100.000000,100.000000,0.0
United States Territories (Shift),100.000000,100.000000,100.000000,0.0
United States Virgin Islands,45.454545,45.454545,45.454545,0.0
Upper-middle-income countries,52.000000,68.000000,52.000000,0.0
Uruguay,43.478261,43.478261,43.478261,0.0
Uzbekistan,0.000000,0.000000,0.000000,0.0
Vanuatu,45.454545,45.454545,45.454545,0.0
Venezuela,52.000000,68.000000,52.000000,0.0
Vietnam,51.587302,67.460317,51.587302,0.0
Wake Island (EIA),100.000000,100.000000,100.000000,0.0
Wake Island (Shift),100.000000,100.000000,100.000000,0.0
West Germany,100.000000,100.000000,100.000000,0.0
Western Africa (EI),0.000000,33.333333,100.000000,0.0
Western Europe (EIA),100.000000,100.000000,100.000000,0.0
Western Sahara,77.272727,77.272727,77.272727,0.0
World,51.587302,67.460317,51.587302,0.0
Yemen,44.444444,44.444444,44.444444,0.0
Yugoslavia,100.000000,100.000000,100.000000,0.0
Zambia,80.000000,80.000000,80.000000,0.0
Zimbabwe,80.000000,80.000000,80.000000,0.0

The distribution of missing values over time shows a substantial decrease in missing data around the year 2000.

However, missing values do not necessarily mean that wind power generation was zero. They may indicate either the absence of wind power generation or a lack of reported data for a particular country and year.

Therefore, before replacing missing values with zeros, the data should be examined at the country level. If missing values occur mainly before the development of the wind power industry and are followed by low initial values and a gradual increase in generation, treating some of these missing values as zero may be reasonable.

On the other hand, missing values occurring between years with substantial wind generation should not be automatically replaced with zero, as they may represent missing observations rather than actual zero generation.

Further data inspection and cleaning will therefore be performed using SQL.

#Part 1

# Data Inspection and Cleaning in DuckDB

In [ ]:
import pandas as pd
pd.set_option("display.max_columns", None)
!wget https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/owid-energy-data.csv
df_row = pd.read_csv("owid-energy-data.csv")

--2026-08-25 20:48:35--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/owid-energy-data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11225068 (11M) [text/plain]
Saving to: ‘owid-energy-data.csv’

owid-energy-data.cs 100%[===================>]  10.70M  --.-KB/s    in 0.06s

2026-08-25 20:48:36 (186 MB/s) - ‘owid-energy-data.csv’ saved [11225068/11225068]

In [ ]:
import duckdb
# Create a DuckDB connection
con = duckdb.connect()

In [ ]:
# Load the raw dataset into DuckDB
con.execute("""
CREATE OR REPLACE TABLE df AS
SELECT *
FROM df_row
""")

#Initial inspection of wind data

First, the availability of wind generation data is examined for each country.

In [ ]:
# Check the number of observations and available wind generation data by country
result = con.execute("""
    SELECT
        country,
        COUNT(*) AS total_rows,
        COUNT(wind_electricity) AS wind_available
    FROM df
    GROUP BY country
    ORDER BY total_rows DESC
""").fetchdf()

display(result)

                   country  total_rows  wind_available
0                Australia         126              61
1                  Austria         126              61
2               Bangladesh         126              61
3                  Belgium         126              61
4                  Bolivia         126              26
..                     ...         ...             ...
309             Montenegro          21               9
310  Serbia and Montenegro          14               0
311            South Sudan          13              13
312           East Germany          11               0
313           West Germany          11               0

[314 rows x 3 columns]

#Checking the effect of regional and aggregate entities

In [ ]:
display(con.execute("""
SELECT DISTINCT
    country,
    iso_code
FROM df
WHERE iso_code IS NULL
ORDER BY country
""").fetchdf())

#Completing missing ISO codes

The relevant historical entities are assigned identifiers so that they can be included in the country-level analysis.

In [ ]:
con.execute("""
UPDATE df
SET iso_code = CASE
        WHEN country = 'Kosovo' THEN 'XKX'
        WHEN country = 'Czechoslovakia' THEN 'OWID_CZE'
        WHEN country = 'East Germany' THEN 'OWID_GDR'
        WHEN country = 'West Germany' THEN 'OWID_GFR'
        WHEN country = 'USSR' THEN 'OWID_USSR'
        WHEN country = 'Yugoslavia' THEN 'OWID_YUG'
        WHEN country = 'Serbia and Montenegro' THEN 'OWID_SRM'
    ELSE iso_code
END
WHERE iso_code IS NULL;
""")

#Checking the updated ISO codes

In [ ]:
display(con.execute("""
SELECT DISTINCT
    country,
    iso_code
FROM df
WHERE country IN (
    'Kosovo',
    'Czechoslovakia',
    'East Germany',
    'West Germany',
    'USSR',
    'Yugoslavia',
    'Serbia and Montenegro'
)
ORDER BY country
""").fetchdf())

#Identifying the first observed wind generation

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE first_wind AS
SELECT
    country,
    year AS first_wind_year,
    iso_code,
    wind_electricity AS first_wind_value
FROM (
    SELECT
        country,
        year,
        iso_code,
        wind_electricity,
        ROW_NUMBER() OVER (
            PARTITION BY country
            ORDER BY year
        ) AS rn
    FROM df
    WHERE wind_electricity IS NOT NULL
      AND wind_electricity > 0
)
WHERE rn = 1;
""").fetchdf()

first_wind = con.execute("""
    SELECT *
    FROM first_wind
""").fetchdf()

display(first_wind)

                           country  first_wind_year iso_code  first_wind_value
0                    ASEAN (Ember)             2005     None          0.020000
1                          Austria             1997      AUT          0.020000
2                             Chad             2016      TCD          0.010000
3                           Greece             1987      GRC          0.001000
4                     OECD (Ember)             2000     None         28.709999
..                             ...              ...      ...               ...
149                    New Zealand             1992      NZL          0.000691
150                         Norway             1993      NOR          0.010000
151                        Reunion             2007      REU          0.010000
152                       Slovakia             2004      SVK          0.010000
153  Upper-middle-income countries             1990     None          0.003020

[154 rows x 4 columns]

The first_wind table contains the first observed positive wind generation value for each country. It is used as an intermediate table for investigating whether missing values before the first observation can reasonably be interpreted as zero generation.

The ROW_NUMBER() window function assigns a sequential number to observations within each country after sorting them by year. This makes it possible to select the first positive observation for each country.

# Comparing the first observation with global wind generation

The first observed value is compared with total wind generation reported for the world in the same year.

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE wind_first_share AS



SELECT
    f.country,
    f.iso_code,
    f.first_wind_year AS year,
    f.first_wind_value AS first_wind,
    w.world_wind,
    100.0 * f.first_wind_value / w.world_wind AS share
FROM first_wind f
JOIN (
    SELECT
        year,
        SUM(wind_electricity) AS world_wind
    FROM df
    WHERE iso_code IS NOT NULL
    GROUP BY year
) w
ON f.first_wind_year = w.year;
""")
display(con.execute("""
SELECT *
FROM wind_first_share
WHERE iso_code IS NOT NULL
ORDER BY share DESC
""").fetchdf())

The world_share value represents the country's first observed positive wind generation as a percentage of total wind generation reported for the same year.

This comparison is used as an indicator of how significant the first observed value is relative to global wind generation.

#Grouping countries by the significance of the first observation

To make the distribution easier to inspect, countries are grouped according to their share of global wind generation.

In [ ]:
share_grad = con.execute("""
SELECT
    CASE
        WHEN world_share < 0.01 THEN '<0.01%'
        WHEN world_share < 0.1 THEN '0.01–0.1%'
        WHEN world_share < 1 THEN '0.1–1%'
        WHEN world_share < 5 THEN '1–5%'
        WHEN world_share < 10 THEN '5–10%'
        ELSE '>10%'
    END AS share_group,
    COUNT(*) AS countries
FROM  wind_first_share
GROUP BY share_group
ORDER BY share_group;
""").fetchdf()
display(share_grad)

#Checking unusually large shares

The results are checked for cases where a country's first observed value accounts for a very large proportion of global generation.

In [ ]:
year_nan = con.execute("""
SELECT country,
       wind_electricity,
       SUM(wind_electricity) OVER () AS world_wind
FROM df WHERE iso_code IS NOT NULL
AND year = 1978
""").fetchdf()
display(year_nan)

Most observations without an ISO code correspond to regional or aggregate entities. However, several historical entities also appear without an ISO code and require separate treatment

#Checking countries with no wind generation observations

The data are further examined to distinguish between countries with no reported wind data and countries whose available observations contain only zero values.

In [ ]:

display(con.execute("""
SELECT
    country,
    COUNT(*) AS rows,
    COUNT(wind_electricity) AS non_null,
    COUNT(*) FILTER (
        wind_electricity > 0
    ) AS positive,
    COUNT(*) FILTER (
        wind_electricity = 0
    ) AS zero,
    MAX(wind_electricity) AS max_wind
FROM df
WHERE country IN (
    'Kosovo',
    'Czechoslovakia',
    'East Germany',
    'West Germany',
    'USSR',
    'Yugoslavia',
    'Serbia and Montenegro'
)
GROUP BY country
ORDER BY country
""").fetchdf())

                 country  rows  non_null  positive  max_wind
0         Czechoslovakia    93         0       0.0       NaN
1           East Germany    11         0       0.0       NaN
2                 Kosovo    26        14       8.0       0.4
3  Serbia and Montenegro    14         0       0.0       NaN
4                   USSR    92        20       0.0       0.0
5           West Germany    11         0       0.0       NaN
6             Yugoslavia    92         0       0.0       NaN

This check shows that the absence of positive observations can have different meanings: some countries have explicit zero values, while others have missing wind generation data altogether.

Therefore, missing values should not be treated as zero solely on the basis of a country's lack of positive observations.

#Selecting countries for further treatment

Based on the previous checks, countries are separated into groups according to the available information.

Countries with a very small first observed value are considered candidates for treating missing values as zero, while countries with a more substantial first observation require additional attention.

In [ ]:
countries_to_zero = con.execute("""

SELECT
    country,
    iso_code,
    year AS first_wind_year,
    first_wind,
    world_wind,
    share
FROM wind_first_share
WHERE share < 0.1
  AND iso_code IS NOT NULL
ORDER BY share

""").fetchdf()

display(countries_to_zero)

         country iso_code  first_wind_year  first_wind   world_wind     share
0    El Salvador      SLV             2020       0.010  1591.470005  0.000628
1   Saudi Arabia      SAU             2019       0.010  1420.959998  0.000704
2           Oman      OMN             2019       0.010  1420.959998  0.000704
3     Martinique      MTQ             2018       0.010  1268.140000  0.000789
4        Somalia      SOM             2017       0.010  1139.440014  0.000878
..           ...      ...              ...         ...          ...       ...
92      Colombia      COL             2004       0.050    85.480001  0.058493
93    Luxembourg      LUX             1998       0.010    15.937996  0.062743
94       Tunisia      TUN             2000       0.020    31.150000  0.064205
95         Italy      ITA             1989       0.002     2.649777  0.075478
96        Turkey      TUR             1999       0.020    21.087146  0.094845

[97 rows x 6 columns]

Countries with a significant first observed value, as well as countries with no wind generation observations, are collected separately for further research.

In [ ]:
countries_to_research = con.execute("""
SELECT
    country,
    iso_code,
    year AS first_wind_year,
    first_wind,
    world_wind,
    share,
    'significant_first_wind' AS reason
FROM wind_first_share
WHERE share >= 0.1
  AND iso_code IS NOT NULL

UNION ALL

SELECT
    country,
    iso_code,
    NULL AS first_wind_year,
    NULL AS first_wind,
    NULL AS world_wind,
    NULL AS share,
    'no_data' AS reason
FROM df
WHERE iso_code IS NOT NULL
GROUP BY country, iso_code
HAVING COUNT(wind_electricity) = 0

ORDER BY country
""").fetchdf()

display(countries_to_research)

,country,iso_code,first_wind_year,first_wind,world_wind,share,reason
0,Antarctica,ATA,<NA>,NaN,NaN,NaN,no_data
1,Argentina,ARG,1996,0.009618,9.217319,0.104347,significant_first_wind
2,Austria,AUT,1997,0.020000,11.985472,0.166869,significant_first_wind
3,Belgium,BEL,1987,0.006000,0.195377,3.070989,significant_first_wind
4,Cambodia,KHM,<NA>,NaN,NaN,NaN,no_data
5,Canada,CAN,1985,0.001000,0.064220,1.557142,significant_first_wind
6,Costa Rica,CRI,2000,0.180000,31.150000,0.577849,significant_first_wind
7,Curacao,CUW,<NA>,NaN,NaN,NaN,no_data
8,Czechoslovakia,OWID_CZE,<NA>,NaN,NaN,NaN,no_data
9,Denmark,DNK,1978,0.003000,0.003000,100.000000,significant_first_wind
10,East Germany,OWID_GDR,<NA>,NaN,NaN,NaN,no_data
11,Finland,FIN,1994,0.010000,7.639516,0.130898,significant_first_wind
12,France,FRA,1996,0.010000,9.217319,0.108491,significant_first_wind
13,French Guiana,GUF,<NA>,NaN,NaN,NaN,no_data
14,Germany,DEU,1986,0.001000,0.138831,0.720299,significant_first_wind
15,Greece,GRC,1987,0.001000,0.195377,0.511832,significant_first_wind
16,India,IND,1990,0.030303,3.632010,0.834332,significant_first_wind
17,Iran,IRN,1999,0.035000,21.087146,0.165978,significant_first_wind
18,Ireland,IRL,1992,0.010000,4.747164,0.210652,significant_first_wind
19,Micronesia (country),FSM,<NA>,NaN,NaN,NaN,no_data
20,Morocco,MAR,2000,0.060000,31.150000,0.192616,significant_first_wind
21,Netherlands,NLD,1986,0.001000,0.138831,0.720299,significant_first_wind
22,Netherlands Antilles,ANT,<NA>,NaN,NaN,NaN,no_data
23,Northern Mariana Islands,MNP,<NA>,NaN,NaN,NaN,no_data
24,Norway,NOR,1993,0.010000,5.768026,0.173370,significant_first_wind
25,Serbia and Montenegro,OWID_SRM,<NA>,NaN,NaN,NaN,no_data
26,Spain,ESP,1989,0.013000,2.649777,0.490607,significant_first_wind
27,Sweden,SWE,1983,0.003000,0.032795,9.147750,significant_first_wind
28,Tuvalu,TUV,<NA>,NaN,NaN,NaN,no_data
29,United Kingdom,GBR,1989,0.009000,2.649777,0.339651,significant_first_wind
30,United States,USA,1983,0.002695,0.032795,8.217576,significant_first_wind
31,West Germany,OWID_GFR,<NA>,NaN,NaN,NaN,no_data
32,Yugoslavia,OWID_YUG,<NA>,NaN,NaN,NaN,no_data

#Additional validation of country groups

Before creating the final dataset, the number and composition of the country groups are checked.

In [ ]:
all_with_iso = con.execute("""
SELECT DISTINCT
    country,
    iso_code,
    sum(wind_electricity)
FROM df
WHERE iso_code IS NOT NULL
GROUP BY country, iso_code
HAVING COUNT(wind_electricity) > 0
   AND MAX(wind_electricity) = 0
ORDER BY country
""").fetchdf()

display(all_with_iso)

                         country iso_code  sum(wind_electricity)
0                    Afghanistan      AFG                    0.0
1                        Albania      ALB                    0.0
2                 American Samoa      ASM                    0.0
3                         Angola      AGO                    0.0
4            Antigua and Barbuda      ATG                    0.0
..                           ...      ...                    ...
92  United States Virgin Islands      VIR                    0.0
93                Western Sahara      ESH                    0.0
94                         Yemen      YEM                    0.0
95                        Zambia      ZMB                    0.0
96                      Zimbabwe      ZWE                    0.0

[97 rows x 3 columns]

The number of countries without any wind generation observations is also checked.

In [ ]:
no_wind_data_count = con.execute("""
SELECT COUNT(*) AS countries_no_wind_data
FROM (
    SELECT
        country,
        iso_code
    FROM df
    WHERE iso_code IS NOT NULL
    GROUP BY country, iso_code
    HAVING COUNT(wind_electricity) = 0
)
""").fetchdf()

display(no_wind_data_count)

   countries_no_wind_data
0                      13

Finally, the overall distribution of countries is checked.

In [ ]:
display(con.execute("""
SELECT
    COUNT(*) AS total_countries,

    COUNT(*) FILTER (
        non_null = 0
    ) AS no_data,

    COUNT(*) FILTER (
        non_null > 0
        AND max_wind = 0
    ) AS zero_only,

    COUNT(*) FILTER (
        max_wind > 0
    ) AS has_positive_wind

FROM (
    SELECT
        country,
        iso_code,
        COUNT(wind_electricity) AS non_null,
        MAX(wind_electricity) AS max_wind
    FROM df
    WHERE iso_code IS NOT NULL
    GROUP BY country, iso_code
) t
""").fetchdf())

   total_countries  no_data  zero_only  has_positive_wind
0              227       13         97                117

This provides a final check of the three main categories of countries before the cleaned dataset is created.

#Creating the cleaned wind dataset

After the country-level checks are complete, the variables required for further analysis are selected.

In [ ]:
con.execute("""
CREATE OR REPLACE TABLE wind_data AS

SELECT
    country,
    iso_code,
    gdp,
    population,
    year,
    wind_electricity
FROM df
WHERE iso_code IS NOT NULL
""")

Only observations with an ISO code are retained in the working dataset.

The countries selected for zero replacement are then registered as a temporary DuckDB table.

In [ ]:
con.register("countries_to_zero_df", countries_to_zero)

Missing wind generation values for these countries are replaced with zero.

In [ ]:
con.execute("""
UPDATE wind_data
SET wind_electricity = 0
WHERE country IN (
    SELECT country
    FROM countries_to_zero_df
)
AND wind_electricity IS NULL
""")

DuckDB's UPDATE statement modifies only the rows satisfying the specified conditions, while other columns and rows remain unchanged.

#Validating the cleaned dataset

The number of total, non-null, and remaining null wind generation values is checked for each country.

In [ ]:
display(con.execute("""
SELECT
    country,
    iso_code,
    gdp,
    population,
    COUNT(*) AS rows_total,
    COUNT(wind_electricity) AS values_after_cleaning,
    COUNT(*) - COUNT(wind_electricity) AS remaining_null
FROM wind_data
GROUP BY country, iso_code, gdp, population
ORDER BY country
""").fetchdf())

,country,iso_code,gdp,population,rows_total,values_after_cleaning,remaining_null
0,Afghanistan,AFG,NaN,4751177.0,1,0,1
1,Afghanistan,AFG,1.267754e+10,13278983.0,1,0,1
2,Afghanistan,AFG,NaN,5044212.0,1,0,1
3,Afghanistan,AFG,NaN,5504191.0,1,0,1
4,Afghanistan,AFG,NaN,7119235.0,1,0,1
...,...,...,...,...,...,...,...
17385,Zimbabwe,ZWE,2.381884e+10,14207367.0,1,1,0
17386,Zimbabwe,ZWE,2.424616e+10,14399008.0,1,1,0
17387,Zimbabwe,ZWE,2.557601e+10,14812484.0,1,1,0
17388,Zimbabwe,ZWE,2.678627e+10,15034457.0,1,1,0
17389,Zimbabwe,ZWE,NaN,2072976.0,1,0,1

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

The remaining missing values are then examined separately.

In [ ]:
display(con.execute("""
SELECT
    country,
    iso_code,
    COUNT(*) AS total_rows,
    COUNT(wind_electricity) AS non_null,
    COUNT(*) - COUNT(wind_electricity) AS null_rows
FROM wind_data
GROUP BY country, iso_code
HAVING (country, iso_code) IN (
    SELECT country, iso_code
    FROM countries_to_zero_df
)
ORDER BY country
""").fetchdf())

            country iso_code  total_rows  non_null  null_rows
0       Afghanistan      AFG         125       125          0
1           Albania      ALB         125       125          0
2           Algeria      DZA         125       125          0
3    American Samoa      ASM          45        45          0
4            Angola      AGO         125       125          0
..              ...      ...         ...       ...        ...
189         Vietnam      VNM         126       126          0
190  Western Sahara      ESH          44        44          0
191           Yemen      YEM          45        45          0
192          Zambia      ZMB         125       125          0
193        Zimbabwe      ZWE         125       125          0

[194 rows x 5 columns]

#Basic validation of population and GDP

Finally, the variables required for subsequent analysis are checked for missing or non-positive values.

In [ ]:
display(con.execute("""
SELECT
    country,
    COUNT(*) AS rows,
    COUNT(population) AS non_null,
    MIN(population) AS min_population,
    MAX(population) AS max_population
FROM wind_data
GROUP BY country
ORDER BY non_null;
""").fetchdf())

In [ ]:
display(con.execute("""
SELECT *
FROM wind_data
WHERE population IS NULL
   OR population <= 0;
""").fetchdf())

The same check is performed for GDP.

In [ ]:
display(con.execute("""
SELECT
    country,
    COUNT(*) AS rows,
    COUNT(gdp) AS non_null,
    MIN(gdp) AS min_gdp,
    MAX(gdp) AS max_gdp
FROM wind_data
GROUP BY country
ORDER BY non_null;
""").fetchdf())

In [ ]:
display(con.execute("""
SELECT *
FROM wind_data
WHERE gdp IS NULL
   OR gdp <= 0;
""").fetchdf())

At this stage, the main cleaning and validation of the wind generation
data are complete. The resulting wind_data table can be used as
the basis for adding derived variables and continuing the analysis.

In [ ]:
con.execute("""
COPY wind_data
TO 'wind_data_clean.csv'
WITH (HEADER, DELIMITER ',')
""")

In [ ]:
import os

os.listdir()

['.config', 'wind_data_clean.csv', 'owid-energy-data.csv', 'sample_data']

In [ ]:
from google.colab import files

files.download('wind_data_clean.csv')

At this stage, we finish cleaning the data and start adding additional indicators.

#Часть 1.1

In [ ]:
'''
# Convert the HDI dataset to UTF-8 so it can be used consistently in the project
# and displayed correctly on GitHub.

!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/HDR25_Composite_indices_complete_time_series.csv?raw=true

import pandas as pd
#df = pd.read_csv("HDR25_Composite_indices_complete_time_series.csv?raw=true")
hdi = pd.read_csv(
    "HDR25_Composite_indices_complete_time_series.csv",
    encoding="latin1"
)
hdi.columns.tolist()


hdi.to_csv(
    "hdi_clean_utf8.csv",
    index=False,
    encoding="utf-8"
)

# Load the cleaned HDI dataset

from google.colab import files

files.download('hdi_clean_utf8.csv')
'''

In [ ]:
!wget https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/hdi_clean_utf8.csv

--2026-09-12 10:31:03--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/hdi_clean_utf8.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2005796 (1.9M) [text/plain]
Saving to: ‘hdi_clean_utf8.csv’

hdi_clean_utf8.csv  100%[===================>]   1.91M  --.-KB/s    in 0.06s

2026-09-12 10:31:03 (33.4 MB/s) - ‘hdi_clean_utf8.csv’ saved [2005796/2005796]

In [ ]:
hdi = pd.read_csv("hdi_clean_utf8.csv")
# Keep the country identifiers and yearly HDI values

In [ ]:
hdi_clean = hdi[
    ["iso3", "country"] +
    [f"hdi_{year}" for year in range(1990, 2024)]
].copy()

# Convert the HDI data from wide format to long format

hdi_long = hdi_clean.melt(
    id_vars=["iso3", "country"],
    var_name="year",
    value_name="hdi"
)

# Convert the year column from strings such as "hdi_1990" to integers

hdi_long["year"] = (
    hdi_long["year"]
    .str.replace("hdi_", "", regex=False)
    .astype(int)
)
display(hdi_long)

           iso3                          country  year    hdi
0           AFG                      Afghanistan  1990  0.285
1           ALB                          Albania  1990  0.654
2           DZA                          Algeria  1990  0.595
3           AND                          Andorra  1990    NaN
4           AGO                           Angola  1990    NaN
...         ...                              ...   ...    ...
6999    ZZG.ECA          Europe and Central Asia  2023  0.818
7000    ZZH.LAC  Latin America and the Caribbean  2023  0.783
7001     ZZI.SA                       South Asia  2023  0.672
7002    ZZJ.SSA               Sub-Saharan Africa  2023  0.568
7003  ZZK.WORLD                            World  2023  0.756

[7004 rows x 4 columns]

In [ ]:
import pandas as pd
import duckdb
con = duckdb.connect()

In [ ]:
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls?raw=true
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls?raw=true
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls?raw=true
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls?raw=true

--2026-09-12 10:31:19--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls [following]
--2026-09-12 10:31:19--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls [following]
--2026-09-12 10:31:20--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 442368 (432K) [application/octet-stream]
Saving to: ‘API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls?raw=true’

API_SP.URB.TOTL.IN. 100%[===================>] 432.00K  --.-KB/s    in 0.03s

2026-09-12 10:31:20 (12.1 MB/s) - ‘API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls?raw=true’ saved [442368/442368]

--2026-09-12 10:31:20--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls [following]
--2026-09-12 10:31:20--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls [following]
--2026-09-12 10:31:20--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 432128 (422K) [application/octet-stream]
Saving to: ‘API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls?raw=true’

API_SP.DYN.LE00.IN_ 100%[===================>] 422.00K  --.-KB/s    in 0.03s

2026-09-12 10:31:20 (12.0 MB/s) - ‘API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls?raw=true’ saved [432128/432128]

--2026-09-12 10:31:20--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls [following]
--2026-09-12 10:31:21--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls [following]
--2026-09-12 10:31:21--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 233472 (228K) [application/octet-stream]
Saving to: ‘API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls?raw=true’

API_IT.NET.USER.ZS_ 100%[===================>] 228.00K  --.-KB/s    in 0.02s

2026-09-12 10:31:21 (9.00 MB/s) - ‘API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls?raw=true’ saved [233472/233472]

--2026-09-12 10:31:21--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls [following]
--2026-09-12 10:31:21--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls [following]
--2026-09-12 10:31:21--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/API_EN.POP.DNST_DS2_en_excel_v2_33667.xls
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 406528 (397K) [application/octet-stream]
Saving to: ‘API_EN.POP.DNST_DS2_en_excel_v2_33667.xls?raw=true’

API_EN.POP.DNST_DS2 100%[===================>] 397.00K  --.-KB/s    in 0.03s

2026-09-12 10:31:22 (11.7 MB/s) - ‘API_EN.POP.DNST_DS2_en_excel_v2_33667.xls?raw=true’ saved [406528/406528]

In [ ]:
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/results/Clean%20wind_data%20with%20gdp%2C%20population.xlsx?raw=true

--2026-09-12 10:32:54--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/results/Clean%20wind_data%20with%20gdp%2C%20population.xlsx?raw=true
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/results/Clean%20wind_data%20with%20gdp,%20population.xlsx [following]
--2026-09-12 10:32:54--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/results/Clean%20wind_data%20with%20gdp,%20population.xlsx
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/results/Clean%20wind_data%20with%20gdp%2C%20population.xlsx [following]
--2026-09-12 10:32:55--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/results/Clean%20wind_data%20with%20gdp%2C%20population.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 671604 (656K) [application/octet-stream]
Saving to: ‘Clean wind_data with gdp, population.xlsx?raw=true’

Clean wind_data wit 100%[===================>] 655.86K  --.-KB/s    in 0.04s

2026-09-12 10:32:55 (15.2 MB/s) - ‘Clean wind_data with gdp, population.xlsx?raw=true’ saved [671604/671604]

In [ ]:
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx?raw=true

--2026-09-12 10:17:08--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx?raw=true
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx [following]
--2026-09-12 10:17:09--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx [following]
--2026-09-12 10:17:09--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/data_for_analysis/wgidataset_with_sourcedata-2025.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10423344 (9.9M) [application/octet-stream]
Saving to: ‘wgidataset_with_sourcedata-2025.xlsx?raw=true’

wgidataset_with_sou 100%[===================>]   9.94M  --.-KB/s    in 0.1s

2026-09-12 10:17:09 (78.5 MB/s) - ‘wgidataset_with_sourcedata-2025.xlsx?raw=true’ saved [10423344/10423344]

In [ ]:
# Load the datasets used to add socioeconomic and demographic indicators
urb = pd.read_excel("API_SP.URB.TOTL.IN.ZS_DS2_en_excel_v2_169.xls?raw=true", sheet_name=0, skiprows=3)
dyn = pd.read_excel("API_SP.DYN.LE00.IN_DS2_en_excel_v2_33138.xls?raw=true", sheet_name=0, skiprows=3)
net = pd.read_excel("API_IT.NET.USER.ZS_DS2_en_excel_v2_33090.xls?raw=true", sheet_name=0, skiprows=3)
pop = pd.read_excel("API_EN.POP.DNST_DS2_en_excel_v2_33667.xls?raw=true", sheet_name=0, skiprows=3)
# Load the governance and cleaned wind energy datasets
wgit_data = pd.read_excel("wgidataset_with_sourcedata-2025.xlsx?raw=true",  sheet_name=5)

In [ ]:
wind_data = pd.read_excel("Clean wind_data with gdp, population.xlsx?raw=true")

In [ ]:
print(type(wgit_data))

<class 'pandas.core.frame.DataFrame'>

Переделывание всех датасетов из world bank

In [ ]:
# Convert World Bank datasets from wide format to long format
def to_long(df):
    return df.melt(
        id_vars=[
            "Country Name",
            "Country Code",
            "Indicator Name",
            "Indicator Code"
        ],
        var_name="year",
        value_name="value"
    )

# Reshape each World Bank dataset into country-year format
display(urb.head())
print(urb.columns.tolist())
urb_long = to_long(urb)
display(dyn .head())
print(dyn.columns.tolist())
dyn_long = to_long(dyn)
display(net.head())
print(net.columns.tolist())
net_long = to_long(net)
display(pop.head())
print(pop.columns.tolist())
pop_long = to_long(pop)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,59.023670,59.072800,59.212271,59.432359,59.723340,60.075491,...,63.007788,62.776849,62.536764,62.288276,62.002884,61.927534,61.881166,61.835149,61.790940,61.748525
1,Africa Eastern and Southern,AFE,Urban population (% of total population),SP.URB.TOTL.IN.ZS,14.640371,14.867730,15.107367,15.353899,15.607152,15.872246,...,34.881211,35.282987,35.714718,36.097331,36.488322,36.908543,37.360578,37.772301,38.241441,38.702140
2,Afghanistan,AFG,Urban population (% of total population),SP.URB.TOTL.IN.ZS,8.122551,8.389595,8.662664,8.942709,9.231134,9.529343,...,24.658835,24.835282,24.999165,25.143726,25.262210,25.347862,25.393925,25.473053,25.700735,25.940164
3,Africa Western and Central,AFW,Urban population (% of total population),SP.URB.TOTL.IN.ZS,13.946480,14.468419,15.017383,15.592318,16.190616,16.814048,...,48.186274,48.761009,49.332676,49.905469,50.492321,51.089419,51.700103,52.302109,52.878824,53.477205
4,Angola,AGO,Urban population (% of total population),SP.URB.TOTL.IN.ZS,10.387104,10.810545,11.207060,11.581720,11.945180,12.308095,...,64.299230,65.085053,65.873214,66.663782,67.456827,68.252416,69.050619,69.851503,70.655138,71.461592

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.049000,64.215000,64.602000,64.944000,65.303000,65.615000,...,75.540000,75.620000,75.880000,76.019000,75.406000,73.655000,76.226000,76.353000,76.500000,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.169658,44.468838,44.877890,45.160583,45.535695,45.770723,...,62.167981,62.591275,63.330691,63.857261,63.766484,62.979999,64.487152,65.146228,65.349930,NaN
2,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.799000,33.291000,33.757000,34.201000,34.673000,35.124000,...,62.646000,62.406000,62.443000,62.941000,61.454000,60.417000,65.617000,66.035000,66.289000,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.779636,38.058973,38.681792,38.936918,39.194375,39.478875,...,56.387563,56.620764,57.030771,57.142827,57.357709,57.355015,57.978995,58.847483,59.041538,NaN
4,Angola,AGO,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.933000,36.902000,37.168000,37.419000,37.704000,37.968000,...,61.619000,62.122000,62.622000,63.051000,63.116000,62.958000,64.246000,64.617000,64.805000,NaN

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,93.542454,97.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.300000,17.30,19.600000,21.600000,23.5000,25.000000,26.800000,27.800000,28.800000,30.4
2,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.000000,13.50,16.799999,17.600000,17.0485,16.514299,15.866300,15.928400,16.094999,NaN
3,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,20.900000,23.80,25.700000,28.500000,31.5000,34.700000,37.500000,38.500000,40.000000,42.4
4,Angola,AGO,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.200001,26.00,29.000000,32.129398,33.3209,34.556499,35.838001,37.885899,40.704800,NaN

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,308.766667,312.888889,316.677778,320.105556,323.277778,...,604.038889,604.083333,605.044444,606.683333,603.261111,598.333333,596.166667,596.438889,NaN,NaN
1,Africa Eastern and Southern,AFE,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,12.036017,12.363810,12.703964,13.060764,13.432961,...,41.980491,43.098783,44.287597,45.503487,46.742560,47.997295,49.258043,50.514698,NaN,NaN
2,Afghanistan,AFG,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,14.127046,14.418849,14.725614,15.047327,15.387222,...,53.203030,54.718328,56.334482,58.041061,59.900616,61.328691,62.215541,63.558501,NaN,NaN
3,Africa Western and Central,AFW,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,11.021477,11.258924,11.505914,11.759627,12.021609,...,47.403025,48.658065,49.901207,51.131317,52.365657,53.613859,54.872708,56.193993,NaN,NaN
4,Angola,AGO,Population density (people per sq. km of land ...,EN.POP.DNST,NaN,4.252493,4.294786,4.338109,4.382921,4.429278,...,23.408254,24.251896,25.103999,25.969064,26.831741,27.699069,28.583484,29.477746,NaN,NaN

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [ ]:
display(wgit_data)
print(wgit_data.columns.tolist())

,ID variable (economy code/ gov. dimension/ year),Economy (name),Economy (code),Region,Income classification,Year,Governance dimension,Number of sources,Governance estimate (approx. -2.5 to +2.5),Standard error (estimate),...,OBI mean,PIA mean,PRS mean,RSF mean,VAB mean,VDM mean,WBS mean,WCY mean,WJP mean,WMO mean
0,ADOcc1996,Andorra,ADO,NaN,NaN,1996,cc,1,1.362621,0.435253,...,..,..,..,..,..,..,..,..,..,0.875
1,AFGcc1996,Afghanistan,AFG,South Asia,Low income,1996,cc,2,-1.717570,0.343049,...,..,..,..,..,..,0.148,..,..,..,0
2,AGOcc1996,Angola,AGO,Sub-Saharan Africa,Lower middle income,1996,cc,4,-1.116075,0.231675,...,..,..,0.5,..,..,0.191,..,..,..,0.125
3,ALBcc1996,Albania,ALB,Europe & Central Asia,Upper middle income,1996,cc,3,-0.837552,0.295562,...,..,..,0.333333,..,..,0.317,..,..,..,0.25
4,AREcc1996,United Arab Emirates,ARE,Middle East & North Africa,High income,1996,cc,4,0.241391,0.231675,...,..,..,0.333333,..,..,0.865,..,..,..,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5368,XKXcc2024,Kosovo,XKX,Europe & Central Asia,Upper middle income,2024,cc,9,-0.254728,0.173881,...,..,0.5,..,..,..,0.727,..,..,0.474907,0.5
5369,YEMcc2024,"Yemen, Rep.",YEM,Middle East & North Africa,Low income,2024,cc,8,-1.635879,0.187685,...,..,0.1,0.166667,..,..,0.089,..,..,..,0
5370,ZAFcc2024,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,2024,cc,11,-0.191793,0.159967,...,..,..,0.416667,..,..,0.445,..,0.137705,0.460917,0.5
5371,ZMBcc2024,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2024,cc,13,-0.456829,0.155605,...,..,0.3,0.333333,..,..,0.645,..,..,0.37553,0.5
5372,ZWEcc2024,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,2024,cc,13,-1.251654,0.155605,...,..,0.3,0.25,..,..,0.182,..,..,0.314383,0.166667

['ID variable (economy code/ gov. dimension/ year)', 'Economy (name)', 'Economy (code)', 'Region', 'Income classification', 'Year', 'Governance dimension', 'Number of sources', 'Governance estimate (approx. -2.5 to +2.5)', 'Standard error (estimate)', 'Lower threshold (90% conf. int. estimate)', 'Upper threshold (90% conf. int. estimate)', 'Governance score (0-100)', 'Standard error (gov. score)', 'Lower threshold (90% conf. int. score)', 'Upper threshold (90% conf. int. score)', 'ADB mean', 'AFR mean', 'ARB mean', 'ASB mean', 'ASD mean', 'BPS mean', 'BTI mean', 'CCR mean', 'EBR mean', 'EIU mean', 'EQI mean', 'EUB mean', 'FRH mean', 'GCB mean', 'GCS mean', 'GII mean', 'GWP mean', 'HER mean', 'HRM mean', 'HUM mean', 'IFD mean', 'IJT mean', 'IRP mean', 'LBO mean', 'MSI mean', 'OBI mean', 'PIA mean', 'PRS mean', 'RSF mean', 'VAB mean', 'VDM mean', 'WBS mean', 'WCY mean', 'WJP mean', 'WMO mean']

In [ ]:
# Register the datasets in DuckDB for SQL-based integration
con.register("hdi_long", hdi_long)
con.register("urb_long", urb_long)
con.register("dyn_long", dyn_long)
con.register("net_long", net_long)
con.register("pop_long", pop_long)

In [ ]:
con.register("wind_data", wind_data)

In [ ]:
con.register("another_raw_data", wgit_data)

In [ ]:
# Combine wind generation data with socioeconomic and demographic indicators
# using country codes and year as the matching keys.

analysis_df = con.execute("""
CREATE OR REPLACE TABLE analysis_data AS

SELECT
    w.country,
    w.iso_code,
    w.year,
    w.population,
    w.gdp,
    w.wind_electricity,

    h.hdi,

    p.value AS population_density,
    u.value AS urbanization,
    d.value AS life_expectancy,
    n.value AS network,

    r."Governance score (0-100)" AS corruption

FROM wind_data AS w

LEFT JOIN hdi_long AS h
    ON w.iso_code = h.iso3
   AND w.year = h.year

LEFT JOIN pop_long AS p
    ON w.iso_code = p."Country Code"
   AND w.year = CAST(p.year AS INTEGER)

LEFT JOIN urb_long AS u
    ON w.iso_code = u."Country Code"
   AND w.year = CAST(u.year AS INTEGER)

LEFT JOIN dyn_long AS d
    ON w.iso_code = d."Country Code"
   AND w.year = CAST(d.year AS INTEGER)

LEFT JOIN net_long AS n
    ON w.iso_code = n."Country Code"
   AND w.year = CAST(n.year AS INTEGER)

LEFT JOIN another_raw_data AS r
    ON w.iso_code = r."Economy (code)"
   AND w.year = CAST(r."Year" AS INTEGER);
""").fetchdf()

In [ ]:
display(con.execute("""
    SELECT *
    FROM analysis_data
""").fetchdf())

,country,iso_code,year,population,gdp,wind_electricity,hdi,population_density,urbanization,life_expectancy,network,corruption
0,Afghanistan,AFG,1996,17763266.0,1.207013e+10,0.00,0.334,27.234666,17.959649,52.830,NaN,13.088573
1,Afghanistan,AFG,1998,19159996.0,1.169217e+10,0.00,0.338,29.376134,18.235814,52.487,NaN,14.874579
2,Afghanistan,AFG,2000,20130334.0,1.128379e+10,0.00,0.351,30.863847,18.558200,55.005,NaN,14.710319
3,Afghanistan,AFG,2002,21378123.0,1.880487e+10,0.00,0.383,32.776961,18.941248,56.225,0.004561,16.613494
4,Afghanistan,AFG,2003,22733053.0,2.107434e+10,0.00,0.392,34.854344,19.160035,57.171,0.087891,16.573827
...,...,...,...,...,...,...,...,...,...,...,...,...
17599,Venezuela,VEN,2024,28405544.0,NaN,0.02,NaN,NaN,89.285860,72.673,76.678902,15.728676
17600,Vietnam,VNM,2024,100987685.0,NaN,12.75,NaN,NaN,38.490070,74.736,84.150000,42.760055
17601,Yemen,YEM,2024,40583173.0,NaN,0.00,NaN,NaN,36.807752,69.439,NaN,14.742134
17602,Zambia,ZMB,2024,21314962.0,NaN,0.00,NaN,NaN,45.470384,66.528,17.101000,38.607899
17603,Zimbabwe,ZWE,2024,16634366.0,NaN,0.00,NaN,NaN,39.893372,63.064,41.642799,22.519426

In [ ]:
#Export the final integrated dataset for further analysis
con.execute("""
COPY analysis_data
TO 'analysis_data.csv'
WITH (HEADER, DELIMITER ',')
""")

In [ ]:
from google.colab import files

files.download("analysis_data.csv")

#Часть 2
Глубокая аналитика с помощью питона

In [ ]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr

In [ ]:
!wget https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/analysis_data_clean_final.xlsx?raw=true

--2026-09-09 17:21:52--  https://github.com/smell0of0chamomile/wind_energy_analysis/blob/main/analysis_data_clean_final.xlsx?raw=true
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/analysis_data_clean_final.xlsx [following]
--2026-09-09 17:21:53--  https://github.com/smell0of0chamomile/wind_energy_analysis/raw/refs/heads/main/analysis_data_clean_final.xlsx
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/analysis_data_clean_final.xlsx [following]
--2026-09-09 17:21:53--  https://raw.githubusercontent.com/smell0of0chamomile/wind_energy_analysis/refs/heads/main/analysis_data_clean_final.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2322910 (2.2M) [application/octet-stream]
Saving to: ‘analysis_data_clean_final.xlsx?raw=true’

analysis_data_clean 100%[===================>]   2.21M  --.-KB/s    in 0.1s

2026-09-09 17:21:54 (14.8 MB/s) - ‘analysis_data_clean_final.xlsx?raw=true’ saved [2322910/2322910]

In [ ]:
df = pd.read_excel("analysis_data_clean_final.xlsx?raw=true", sheet_name='analysis_data_clean_gdp')

In [ ]:
df.describe()

,year,wind_electricity,gdp,hdi,population,urbanization,density,network,corruption
count,17604.000000,15807.000000,1.176200e+04,5820.000000,10344.000000,6064.000000,11021.000000,6064.000000,5208.000000
mean,1974.929448,1.431848,3.216750e+11,0.680211,278.862998,31.549237,66.563933,31.549237,47.296815
std,35.908542,20.706855,1.233118e+12,0.164746,1346.377512,32.441724,10.483806,32.441724,20.123503
min,1900.000000,0.000000,1.642060e+08,0.215000,0.098625,0.000000,12.158000,0.000000,6.061704
25%,1946.000000,0.000000,1.424012e+10,0.560000,20.332803,1.782897,59.961000,1.782897,31.711416
50%,1984.000000,0.000000,4.339041e+10,0.703000,67.821262,18.300000,69.347000,18.300000,43.329255
75%,2005.000000,0.000000,1.817052e+11,0.806000,155.636587,61.087876,74.189098,61.087876,62.012974
max,2025.000000,1135.439941,2.696600e+13,0.972000,21530.000000,100.000000,85.532683,100.000000,98.131955

In [ ]:
df.columns.tolist()

['country',
 'iso_code',
 'year',
 'wind_electricity',
 'gdp',
 'hdi',
 'population',
 'urbanization',
 'density',
 'network',
 'corruption']

In [ ]:
factors = [
    "gdp",
    "hdi",
    "population",
    "urbanization",
    "density",
    "network",
    "corruption"
]

target = "wind_electricity"

In [ ]:
def correlation_analysis(df, target, factors):

    results = []

    for factor in factors:

        data = df[[target, factor]].dropna()

        pearson_r, pearson_p = pearsonr(
            data[target],
            data[factor]
        )

        spearman_r, spearman_p = spearmanr(
            data[target],
            data[factor]
        )

        results.append({
            "factor": factor,
            "n": len(data),
            "pearson_r": pearson_r,
            "pearson_p": pearson_p,
            "spearman_r": spearman_r,
            "spearman_p": spearman_p
        })

    return pd.DataFrame(results)

In [ ]:
correlation_results = correlation_analysis(
    df,
    target="wind_electricity",
    factors=factors
)

correlation_results

         factor      n  pearson_r     pearson_p  spearman_r     spearman_p
0           gdp  10513   0.716712  0.000000e+00    0.462883   0.000000e+00
1           hdi   5718   0.123651  6.340016e-21    0.569443   0.000000e+00
2    population  10089  -0.009325  3.489843e-01    0.102455   5.912870e-25
3  urbanization   5976   0.154839  2.192165e-33    0.545738   0.000000e+00
4       density  10674   0.095505  4.668116e-23    0.500679   0.000000e+00
5       network   5976   0.154839  2.192165e-33    0.545738   0.000000e+00
6    corruption   5101   0.093004  2.828111e-11    0.363971  1.370297e-159